### ISSUE TITLE
usage with exwm

### ISSUE THREAD

**Issue by 11111000000** [tumashu/helm-posframe#1]
posframe displays under any xorg window

**Comment by tumashu** [comment]
At the moment, emacs seem to do not allow child-frame to the top of other app's window. this is impossible feature at the moment.

**Comment by tumashu** [comment]
At the moment, emacs seem to do not allow child-frame to the top of other app's window. this is impossible feature at the moment.

**Comment by spacekitteh** [comment]
Any update on this?

**Comment by tumashu** [comment]
seem no.

**Comment by nanjigen** [comment]
It seems [this](https://github.com/ch11ng/exwm/issues/550#issuecomment-546653728) fixes it for me. The `helm` equivalent that I use is:

`(setq helm-posframe-parameters '((parent-frame nil)))`
